server:
  port: 8769
  
spring:
  application:
    name: zephyr-service-zuul
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    api-a:
      path: /api-a/**
      service-id: zephyr-service-ribbon
    api-b:
      path: /api-b/**
      service-id: zephyr-service-feign