server:
  port: 8082
  
spring:
  profiles:
    active:
    - cookie-route
    
---
spring:
  cloud:
    gateway:
      routes:
      - id: cookie-route
        uri:
          http://httpbin.org:80/get
        predicates:
        - Cookie=name, zephyr
  profiles:
    active:
    - cookie-route