server:
  port: 8082
  
spring:
  profiles:
    active:
    - header-route
    
---

spring:
  cloud:
    gateway:
      routes:
      - id: header-route
        uri:
          http://httpbin.org:80/get
        predicates:
        - Header=X-Request-Id, \d+
  
  profiles:
    active:
    - header-route
    