server:
  port: 8082

spring:
  profiles:
    active:
    - after-route
    
---

spring:
  cloud:
    gateway:
      routes:
      - id: after-route
        uri:
          http://httpbin.org:80/get
        predicates:
        - After=2019-03-18T14:44:30.789-07:00[America/Denver]
  profiles:
    active:
    - after-route