server:
  port: 8082
  
spring:
  cloud:
    gateway:
      routes:
      - id: limiter-route
        uri:
          http://httpbin.org:80/get
        predicates:
        - After=2019-03-18T15:42:47.789-07:00[America/Denver]
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 3
  application:
    name: zephyr-gateway-limiter
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1